request-repeats: 3
timeout: 5
allow-redirect: true
allow-code-blocks: false
ignore-external: false
white-list-internal:
  - "mailto:sales@gravitational.com"
  - "mailto:info@gravitational.com"
  - "mailto:ben@gravitational.com"
white-list-external:
  - "https://<proxy-host>:3080"
  - "https://auth.example.com:3080/web/newuser/22e3acb6a0c2cde22f13bdc879ff9d2a"
  - "https://proxy.example.com:3080/v1/webapi/oidc/callback"
  - "https://[HOST]:3080/web/sessions"
  - "https://proxyhost:3080"
  - "https://localhost:3080/v1/webapi/saml/acs"
  - "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"
  - "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname\"_"
  - "http://schemas.xmlsoap.org/claims/Group"
  - "https://teleport.example.com:3080/v1/webapi/oidc/callback"
  - "https://teleport.example.com/v1/webapi/saml/acs"
  - "https://teleport-proxy.example.com:3080/v1/webapi/saml/acs"
  - "http://127.0.0.1:3000/metrics"
  - "http://127.0.0.1:3000/healthz"
  - "http://127.0.0.1:3000/readyz"
  - "http://127.0.0.1:3000/debug/pprof"
  - "https://app.onelogin.com/saml/metadata/123456"
  - "https://en.wikipedia.org/wiki/Shebang_(Unix"
  - "https://teleport.example.com:8443"
  - "https://teleport.example.com"
  - "https://[route53_domain](#route53_domain"
  - "https://github.com/gravitational/teleport/blob/master/docker/teleport-quickstart.yml"
  - "https://github.com/gravitational/teleport/blob/master/docker/teleport-ent-quickstart.yml"
  - "https://kubernetes.io/docs/reference/access-authn-authz/rbac/"
  - "https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation"
  - "https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-uhc-hmac-credentials-main"
  - "https://[cluster-url]:3080/web/cluster/[cluster-name]/apps"
  - "https://[cluster-url]:3080/web/cluster/[cluster-name]/apps:"
black-list:
  - "./architecture/teleport-architecture.md"
  - "./quickstart__archive.md"
files:
  - path: "./pages/aws-terraform-guide.md"
    config:
      white-list-internal:
        - "#cluster_name"
        - "#key_name"
        - "#route53_domain"
        - "#route53_zone"
        - "#s3_bucket_name"