clusterName: test-cluster
chartMode: custom
highAvailability:
  replicaCount: 3
  certManager:
    addCommonName: true
    enabled: true
    issuerGroup: custom.cert-manager.io
    issuerName: custom
    issuerKind: CustomClusterIssuer
    usages:
      - server auth
      - client auth
