version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: /examples/go-client
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: /api
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /docker
  schedule:
    interval: daily
