authToken: auth-token
proxyAddr: proxy.example.com:3080
roles: jamf
jamfApiEndpoint: "https://testjamf.jamfcloud.com/api"
jamfUsername: teleport-jamf
jamfCredentialsSecret:
  create: false
  name: existing-teleport-jamf-secret
