[workspace]
resolver = "2"
members = [
    "lib/srv/desktop/rdp/rdpclient",
    "web/packages/teleport/src/ironrdp"
]

[workspace.package]
edition = "2021"
license = "AGPL-3.0-only"
homepage = "https://github.com/gravitational/teleport"
repository = "https://github.com/gravitational/teleport"
publish = false

[profile.dev]
debug = 1
lto = "off"

[profile.release]
debug = 1
codegen-units = 1

[workspace.dependencies]
# Note: To use a local IronRDP repository as a crate (for example, ironrdp-cliprdr), define the dependency as follows:
# ironrdp-cliprdr = { path = "/path/to/local/IronRDP/crates/ironrdp-cliprdr" }
# TODO: this rev hash is temporary, change once https://github.com/Devolutions/IronRDP/pull/424 is merged.
#ironrdp-cliprdr = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-connector = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-displaycontrol = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-dvc = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-graphics = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-pdu = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-rdpdr = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-rdpsnd = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-session = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-svc = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }
#ironrdp-tls = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9", features = ["rustls"]}
#ironrdp-tokio = { git = "https://github.com/Devolutions/IronRDP", rev = "10c2415348e0ddfc097d87099c61a33088e908b9" }

ironrdp-cliprdr = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-cliprdr" }
ironrdp-connector = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-connector" }
ironrdp-displaycontrol = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-displaycontrol" }
ironrdp-dvc = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-dvc" }
ironrdp-graphics = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-graphics" }
ironrdp-pdu = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-pdu" }
ironrdp-rdpdr = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-rdpdr" }
ironrdp-rdpsnd = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-rdpsnd" }
ironrdp-session = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-session" }
ironrdp-svc = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-svc" }
ironrdp-tls = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-tls", features = ["rustls"]}
ironrdp-tokio = { path = "/Users/ibeckermayer/Devolutions/IronRDP/crates/ironrdp-tokio" }
