apiVersion: v2
appVersion: 10.0.0-dev
description: Teleport is a unified access plane for your infrastructure
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
- Teleport
name: teleport-cluster
version: 10.0.0-dev
