name: teleport-auto-trustedcluster
apiVersion: v2
version: 0.0.8
appVersion: "6"
description: Teleport trusted cluster installation which automatically joins itself back to the provided root cluster.
icon: https://goteleport.com/images/logos/logo-teleport-square.svg
keywords:
  - Teleport Enterprise
