apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    {{- include "teleport-cluster.labels" . | indent 4 }}
{{- if .Values.annotations.serviceAccount }}
  annotations:
{{- toYaml .Values.annotations.serviceAccount | nindent 4 }}
{{- end -}}