{{- if .Values.rbac.create -}}
{{- $auth := mustMergeOverwrite (mustDeepCopy .Values) .Values.auth -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "teleport-cluster.auth.labels" . | nindent 4 }}
    {{- if $auth.extraLabels.clusterRole }}
    {{- toYaml $auth.extraLabels.clusterRole | nindent 4 }}
    {{- end }}
rules:
- apiGroups:
  - ""
  resources:
  - users
  - groups
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - selfsubjectaccessreviews
  verbs:
  - create

{{ if .Values.operator.enabled }}
- apiGroups:
  - "resources.teleport.dev"
  resources:
  - teleportroles
  - teleportroles/status
  - teleportusers
  - teleportusers/status
  - teleportgithubconnectors
  - teleportgithubconnectors/status
  - teleportoidcconnectors
  - teleportoidcconnectors/status
  - teleportsamlconnectors
  - teleportsamlconnectors/status
  - teleportloginrules
  - teleportloginrules/status
  - teleportprovisiontokens
  - teleportprovisiontokens/status
  - teleportoktaimportrules
  - teleportoktaimportrules/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - create
  - get
  - update

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
{{- end -}}
{{- end -}}
