{{- $auth := mustMergeOverwrite .Values .Values.auth -}}
{{/* $persistence looks like some backward compatibility trick, is this still relevant? */}}
{{- $persistence := (coalesce $auth.standalone $auth.persistence) -}}
{{- if .Values.persistence.enabled }}
  {{/* Disable persistence for aws and gpc modes */}}
  {{- if and (not (eq $auth.chartMode "aws")) (not (eq $auth.chartMode "gcp")) }}
    {{/* No need to create a PVC if we reuse an existing claim */}}
    {{- if not $persistence.existingClaimName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "teleport-cluster.auth.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "persistence.volumeSize is required in chart values" $persistence.volumeSize }}
    {{- end }}
  {{- end }}
{{- end }}
