name: "Update git to 2.18+ on ubuntu"
description: "Updates git to 2.18+ on ubuntu"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        apt-get -y update && apt-get -y install software-properties-common 
        add-apt-repository -y ppa:git-core/ppa
        apt-get -y update && apt-get -y install git
        