apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups: [""]
    resources: ["secrets",]
    verbs: ["get", "delete", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-delete-hook
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-delete-hook
    spec:
      serviceAccountName: {{ .Release.Name }}-delete-hook
      restartPolicy: OnFailure
      containers:
      - name: post-delete-job
        image: alpine/k8s:1.26.0
        command:
        - sh
        - "-c"
        - |
            /bin/sh <<'EOF'
              # list secrets with format {{ .Release.Name }}-.*-state and delete them.
              kubectl get secrets --no-headers=true  | awk '{print $1}' | grep -E -i "{{ .Release.Name }}-.*-state" |  xargs -r kubectl delete secret
              exit 0
            EOF