apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  auth-token: |
    {{ required "authToken is required in chart values" .Values.authToken }}
