# This is an example GCP deployment
# A secret named `teleport-gcp-credentials` must exist in the same namespace and has a key `gcp-credentials.json`
# whose value is a service-account JSON keyfile using GCP's format (produced by the web UI for example).
# Cert-manager must be installed in the cluster with a working Issuer called `letsencrypt-production`
#
# See https://goteleport.com/docs/deploy-a-cluster/helm-deployments/gcp/

chartMode: gcp
clusterName: teleport.example.com                 # Name of your cluster. Use the FQDN you intend to configure in DNS below
gcp:
  projectId: gcpproj-123456                       # Google Cloud project ID
  backendTable: teleport-helm-backend             # Firestore collection to use for the Teleport backend
  auditLogTable: teleport-helm-events             # Firestore collection to use for the Teleport audit log (must be different to the backend collection)
  auditLogMirrorOnStdout: false                   # Whether to mirror audit log entries to stdout in JSON format (useful for external log collectors)
  sessionRecordingBucket: teleport-helm-sessions  # Google Cloud Storage bucket to use for Teleport session recordings
highAvailability:
  replicaCount: 2                                 # Number of replicas to configure
  certManager:
    enabled: true                                 # Enable cert-manager support to get TLS certificates
    issuerName: letsencrypt-production            # Name of the cert-manager Issuer to use (as configured above)
