timeout: 30m
options:
  machineType: E2_HIGHCPU_32
  
  # This build needs to run in environments where the _GITHUB_DEPLOY_KEY_SRC
  # substitution is defined, but also environments where it isn't. The
  # ALLOW_LOOSE option disables GCBs strict checking of substitution usage,
  # so that the build will still run if _GITHUB_DEPLOY_KEY_SRC is not defined.
  substitution_option: ALLOW_LOOSE

steps:
  # Run the integration tests. Actual content of this job depends on the changes
  # detected in the PR
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport7-v0.1.0
    id: run-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash
    args:
      - -c
      - |
        go run ./cmd/integration-tests          \
          -target "$_BASE_BRANCH"               \
          -key-secret "$_GITHUB_DEPLOY_KEY_SRC"
    timeout: 25m
