steps:
  # Set up BCC headers in a volume to replace the incompatible system-level 
  # headers
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport6.2-v0.1.0
    id: configure BCC headers
    volumes: 
      - name: bcc-headers
        path: /usr/include/bcc
    entrypoint: /bin/bash
    args: 
      - -c
      - cp -R /workspace/build.assets/bcc/* /usr/include/bcc

  # Run non-root integration tests. The root user is selected by docker image.
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport6.2-v0.1.0
    id: root-integration-test
    volumes: 
      - name: bcc-headers
        path: /usr/include/bcc
    args: ['make', 'integration-root']
    timeout: 10m

  # Reconfigure the workspace for the non-root user
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:teleport6.2-v0.1.0
    id: reconfigure-for-nonroot-user
    args: ['chown', '-R', 'ci:ci', '/workspace']

  # Run non-root integration tests. The non-root user is selected by docker image.
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-nonroot:teleport6.2-v0.1.0
    id: nonroot-integration-test
    env:
      - TELEPORT_ETCD_TEST="yes"
    volumes: 
      - name: bcc-headers
        path: /usr/include/bcc    
    entrypoint: '/bin/bash'
    args: 
      - '-c'
      - '(make run-etcd &); sleep 1; make integration'
    timeout: 15m

timeout: 20m
options:
  env:
    - GOCACHE=
    - GOMODCACHE=/workspace/.gomodcacheci
  machineType: E2_HIGHCPU_32
  
