timeout: 15m
options:
  machineType: 'E2_HIGHCPU_32'
  
  volumes:
    # A place to put shared state between build steps so that we don't pollute
    # the workspace
    - name: state
      path: '/state'

  env: 
    # Path to a marker file, whose presence indicates that we should skip tests.
    - SKIP_TESTS=/state/skip     

steps:
  # GCB does a shallow checkout for a build, but if we want to check our changes
  # against other branches we'll need to fetch the repo history. This takes less 
  # than 30s at the time of writing, so it is probably not worth tweaking.
  - name: gcr.io/cloud-builders/git
    id: fetch-history
    args: ['fetch', '--unshallow']

  # Run the unit tests. Actual content of this job depends on the changes 
  # detected in the PR
  - name: us-docker.pkg.dev/ci-account/teleport/buildbox-root:v0.1.0
    id: check-tests
    dir: /workspace/.cloudbuild/scripts
    entrypoint: bash 
    args: 
      - -c
      - go run ./unit-tests -w=/workspace -t=$_BASE_BRANCH -c=HEAD