apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range $key, $value := .Values.service.ports }}
{{ if  or (not $.Values.config.highAvailability) (and ($.Values.config.highAvailability) (not (eq $key "authssh")))   }}
    - name: {{ $key }}
{{ toYaml $value | indent 6 }}
 {{ end }}
{{- end }}
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  selector:
    app: {{ template "teleport.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.config.highAvailability }}
    auth: noauth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "teleport.fullname" . }}auth
  labels:
{{ include "teleport.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.config.authServiceType }}
  ports:
    - name: authssh
      port: {{ .Values.ports.authssh.containerPort }}
      targetPort: {{ .Values.ports.authssh.containerPort }}
      protocol: TCP      
{{- if and (semverCompare ">=1.7-0" .Capabilities.KubeVersion.GitVersion) (.Values.service.externalTrafficPolicy) }}
  externalTrafficPolicy: "{{ .Values.service.externalTrafficPolicy }}"
{{- end }}
  selector:
    app: {{ template "teleport.name" . }}
    release: {{ .Release.Name }}
    auth: hasauth
{{- end }}

