{{- $proxy := mustMergeOverwrite (mustDeepCopy .Values) .Values.proxy -}}
{{- $configTemplate := printf "teleport-cluster.proxy.config.%s" $proxy.chartMode -}}
{{- if (contains ":" $proxy.clusterName) -}}
  {{- $split := split ":" $proxy.clusterName -}}
  {{- $maybePort := int $split._1 -}}
  {{- /* Technically helm-example:test could be a valid cluster name, but strings convert to 0 */ -}}
  {{- /* Only fail when numbers are explicitly used */ -}}
  {{- if or (gt $maybePort 0) (hasSuffix ":0" $proxy.clusterName) -}}
    {{- fail "clusterName must not contain a port" -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-proxy
  namespace: {{ .Release.Namespace }}
{{- if $proxy.annotations.config }}
  annotations: {{- toYaml $proxy.annotations.config | nindent 4 }}
{{- end }}
data:
  teleport.yaml: |2
    {{- mustMergeOverwrite (include $configTemplate . | fromYaml) $proxy.teleportConfig | toYaml | nindent 4 -}}
