# This workflow is required to ensure that required Github check passes even if
# the actual "Bloat Check" workflow was skipped due to path filtering. Otherwise
# it will stay forever pending.
#
# See "Handling skipped but required checks" for more info:
#
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
#
# Note both workflows must have the same name.

name: Bloat Check
run-name: Skip Bloat Check

on:
  push:
    paths-ignore:
      - '.github/workflows/bloat.yaml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
    branches:
      - master
      - branch/**

jobs:
  bloat_check:
    name: Bloat Check
    runs-on: ubuntu-latest

    permissions:
      contents: none

    steps:
      - run: 'echo "No code changes"'