name: Build on Windows
run-name: Build on Windows

on:
  push:
    branches:
      - master
  pull_request:
    # We only build tsh on Windows so only consider Go code as tsh doesn't
    # run any Rust.
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: Build tsh tool on Windows
    runs-on: windows-2022-16core

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Get Go version
        id: go-version
        shell: bash
        run: echo "go-version=$(make --no-print-directory print-go-version | tr -d '\n')" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go-version.outputs.go-version }}

      - name: Build
        run: |
          $Env:OS="windows"
          make build/tsh
