name: Build on Mac OS
run-name: Build on Mac OS

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - '.github/workflows/build-macos.yaml'
  merge_group:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'build.assets/Makefile'
      - 'build.assets/Dockerfile*'
      - '.github/workflows/build-macos.yaml'

jobs:
  build:
    name: Build on Mac OS
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: macos-12-xl

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport with teleport.e
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Prepare toolchain
        uses: ./e/.github/actions/prepare-toolchain-mac

      - name: Build
        run: make binaries
