name: Build CI service images
run-name: Build CI service images
on:
  push:
    paths:
      - .github/services/Dockerfile.*
      - examples/etcd/certs/*.pem
    branches:
      - master
  pull_request:
    paths:
      - .github/services/Dockerfile.*
      - examples/etcd/certs/*.pem
    branches:
      - master

jobs:
  build:
    name: Build CI services Docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build etcd image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          file: .github/services/Dockerfile.etcd
          tags: gzigzigzeo/teleport-ci-etcd:latest
          build-args: |
            ETCD_VERSION=3.3.9
          # build on feature branches, push only on main branch
          # push: ${{ github.ref == 'refs/heads/main' }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}