name: Build on Windows
run-name: Build on Windows

on:
  pull_request:
  push:
  
jobs:
  build:
    name: Build tsh tool on Windows
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          $Env:OS="windows"
          make build/tsh