name: Build on Mac OS
run-name: Build on Mac OS

on:
  pull_request:
  push:
  
jobs:
  build:
    name: Build all tools on Mac OS
    runs-on: macos-12 # macos-latest is Big Sur for now

    permissions:
      contents: read

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Build
        run: make build/tctl build/tsh build/tbot build/teleport