# Workflow will trigger on all pull request (except draft), pull request review, and commit push to a 
# pull request (synchronize) event types
# 
# NOTE: pull_request_target behaves the same as pull_request except it grants a
# read/write token to workflows running on a pull request from a fork. While this 
# may seem unsafe, we are limiting the permissions of the Github token below.
name: Check
on: 
  pull_request_review:
    type: [submitted, edited, dismissed]
  pull_request_target: 
    types: [assigned, opened, reopened, ready_for_review, synchronize]

# Only grant read permissions to PRs and write to actions for the Github token. 
# The default is write permissions to many resources, but it's best 
# practice to keep the scope as small as possible. 
permissions:  
    actions: write
    pull-requests: write
    checks: none
    contents: none
    deployments: none
    issues: none
    packages: none
    repository-projects: none
    security-events: none
    statuses: none

jobs: 
  check-reviews:
    name: Checking reviewers 
    runs-on: ubuntu-latest
    steps:
      # Checkout master branch of Teleport repository. This is to prevent an
      # attacker from submitting their own review assignment logic. 
      - name: Checkout master branch 
        uses: actions/checkout@master
      - name: Installing the latest version of Go.
        uses: actions/setup-go@v2
        # Getting the Github Webflow key to verify commit signatures 
        # from Github when determining whether or not to invalidate 
        # reviews for external contributors. 
      - name: Get Github Webflow Key
        run: curl https://github.com/web-flow.gpg >> github.pgp
        # Note: GPG is already installed on the runner
      - name: Import Key 
        run: gpg --import github.pgp 
        # Remove key once it is imported. It is no longer needed. 
      - name: Remove Key
        run: rm github.pgp
        # Run "check-reviewers" subcommand on bot.
      - name: Checking reviewers
        run: cd .github/workflows && go run cmd/main.go --token=${{ secrets.GITHUB_TOKEN }} --reviewers="${{ secrets.reviewers }}" check-reviewers