name: Check Devbox
run-name: Check Devbox - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:
    paths:
      - 'devbox.json'
      - 'devbox.lock'
      - 'build.assets/flake/**'
  merge_group:
    paths:
      - 'devbox.json'
      - 'devbox.lock'
      - 'build.assets/flake/**'

jobs:
  check-devbox:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    name: Check Devbox
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetpack-io/devbox-install-action@a0bd99f5de03156cc900bbbeb830f07d3d39aab0 # v0.6.1
        with:
          enable-cache: true
          devbox-version: 0.9.1
          sha256-checksum: f58202279237b9e0e7d69ef9334c7ca0628db31e5575f105dad6f41a171ebb6a
