name: Lint (Docs)
run-name: Lint (Docs)
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'docs/**'
      - 'examples/**'
  merge_group:
    paths:
      - 'docs/**'
      - 'examples/**'

jobs:
  doc-tests:
    name: Lint (Docs)
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/docs:latest
      volumes:
        - ${{ github.workspace }}:/src/content/docs

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare config
        run: echo "{\"versions\": [{\"name\": \"docs\", \"branch\": \"$GITHUB_REF_NAME\", \"deprecated\": false}]}" > /src/config.json 

      - name: Test the docs build
        run: yarn install && yarn build

      - name: Run tests
        run: cd /src && yarn markdown-lint
