name: Integration Tests (Root)
run-name: Integration Tests (Root) - ${{ github.run_id }} - @${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    name: Integration Tests (Root)
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: public.ecr.aws/gravitational/teleport-buildbox:teleport12
      options: --cap-add=SYS_ADMIN --privileged

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Run tests
        timeout-minutes: 40
        run: |
          make rdpclient integration-root
