name: Lint (Go)
run-name: make lint
on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "rfd/**"
      - "**/*.md*"
  merge_group:
    paths-ignore:
      - "docs/**"
      - "rfd/**"
      - "**/*.md*"

jobs:
  lint:
    name: Lint (Go)
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport16

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run `go mod tidy`
        run: rm go.sum api/go.sum && go mod tidy && (cd api && go mod tidy)

      - name: Check for no changes after `go mod tidy`
        # We have to add the current directory as a safe directory or else git commands will not work as expected.
        run: git config --global --add safe.directory $( realpath . ) && git diff --exit-code -- go.mod go.sum api/go.mod api/go.sum

      - name: Set linter versions
        run: |
          echo BUF_VERSION=$(cd build.assets; make print-buf-version) >> $GITHUB_ENV
          echo GOLANGCI_LINT_VERSION=$(cd build.assets; make print-golangci-lint-version) >> $GITHUB_ENV

      - name: Print linter versions
        run: |
          echo "BUF_VERSION=$BUF_VERSION"
          echo "GOLANGCI_LINT_VERSION=$GOLANGCI_LINT_VERSION"

      # Run various golangci-lint checks.
      # TODO(codingllama): Using go.work could save a bunch of repetition here.
      - name: golangci-lint (api)
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: api
          args: --out-format=colored-line-number
          skip-cache: true
      - name: golangci-lint (teleport)
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          args: --out-format=colored-line-number --build-tags libfido2,piv
          skip-cache: true
      - name: golangci-lint (assets/backport)
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: assets/backport
          args: --out-format=colored-line-number
          skip-cache: true
      - name: golangci-lint (build.assets/tooling)
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: build.assets/tooling
          args: --out-format=colored-line-number
          skip-cache: true

      - uses: bufbuild/buf-setup-action@88db93f5d74ffa329bb43e42aa95cd822697d214 # v1.29.0
        with:
          github_token: ${{ github.token }}
          version: ${{ env.BUF_VERSION }}
      - uses: bufbuild/buf-lint-action@044d13acb1f155179c606aaa2e53aea304d22058 # v1.1.0
      - name: buf breaking from parent to self
        run: ./build.assets/buf-breaking-with-skip.sh . "https://github.com/${GITHUB_REPOSITORY}.git#branch=${{ github.event.pull_request.base.sha || github.event.merge_group.base_sha }}" ./build.assets/buf-breaking-skip-list
      - name: buf breaking from self to master
        if: ${{ github.base_ref != 'master' && github.event.merge_group.base_ref != 'refs/heads/master' }}
        run: ./build.assets/buf-breaking-with-skip.sh "https://github.com/${GITHUB_REPOSITORY}.git#branch=master" . ./build.assets/buf-breaking-skip-list

      # TODO(codingllama): Consider https://github.com/actions-rs/clippy-check
      #  for Rust.
      - name: Run (non-action) linters
        run: make lint-no-actions

      - name: Check if protos are up to date
        # We have to add the current directory as a safe directory or else git commands will not work as expected.
        run: git config --global --add safe.directory $(realpath .) && make protos-up-to-date/host

      - name: Check if Operator CRDs are up to date
        # We have to add the current directory as a safe directory or else git commands will not work as expected.
        run: git config --global --add safe.directory $(realpath .) && make crds-up-to-date
