name: os-compability-test
run-name: OS compability test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: make build/*
    runs-on: ubuntu-latest
    container: 
      image: public.ecr.aws/gravitational/teleport-buildbox-centos7:teleport12
      env:
        GOCACHE: /tmp/gocache

    steps:
      # https://github.com/gravitational/teleport/pull/18573
      - name: Install git 1.18+
        run: |
          yum -y install git

      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Run make
        run: |
          make build/tctl build/tsh build/tbot build/teleport

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build/

  test-compat:
    needs: build
    name: test-compat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ${{ github.workspace }}/build

      - name: chmod +x
        run: chmod +x ${GITHUB_WORKSPACE}/build/*

      - name: Run compat matrix
        # timeout-minutes: 10 TODO: Uncomment on production runner
        run: |
          cd ${GITHUB_WORKSPACE} && ./build.assets/build-test-compat.sh
