name: OS Compatibility Test
run-name: OS Compatibility Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: OS Compatibility Test
    runs-on: ubuntu-22.04-16core

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox-centos7:teleport12
      env:
        GOCACHE: /tmp/gocache

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Prepare workspace
        uses: ./.github/actions/prepare-workspace

      - name: Run make
        run: |
          make binaries

      - name: Run compat matrix
        timeout-minutes: 10
        run: |
          ./build.assets/build-test-compat.sh
