name: Lint (Terraform)

on:
  push:
    branches:
      - master
      - branch/*
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  pull_request:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  merge_group:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  workflow_dispatch:

jobs:
  terraform-lint:
    uses: gravitational/shared-workflows/.github/workflows/terraform-lint.yaml@edf4063ccd2a1a4623dcae3be443adcefaa3b851
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
