name: Security (Terraform)

on:
  push:
    branches:
      - master
      - branch/*
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  pull_request:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  merge_group:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  workflow_dispatch:

jobs:
  terraform-security:
    uses: gravitational/shared-workflows/.github/workflows/terraform-security.yaml@bb1ea08b3088de8804664493d3d9b14f4742db5a
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write