name: Lint (Terraform)

on:
  push:
    branches:
      - master
      - branch/*
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  pull_request:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  merge_group:
    paths:
      - '**.tf'
      - '**.tf.json'
      - '**.hcl'
  workflow_dispatch:

jobs:
  terraform-lint:
    uses: gravitational/shared-workflows/.github/workflows/terraform-lint.yaml@8aa2a1722c93be4eb7d49be25b451cb8a2e7b02b
    permissions:
      actions: read
      contents: read
      pull-requests: write
      security-events: write
