name: Unit Tests (Helm)
run-name: Unit Tests (Helm) - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:
    paths:
      - '.github/workflows/unit-tests-helm.yaml'
      - 'examples/chart/**'
  merge_group:
    paths:
      - '.github/workflows/unit-tests-helm.yaml'
      - 'examples/chart/**'

jobs:
  test:
    name: Unit Tests (Helm)
    runs-on: ubuntu-latest

    permissions:
      contents: read

    container:
      image: ghcr.io/gravitational/teleport-buildbox:teleport11

    steps:
      - name: Checkout Teleport
        uses: actions/checkout@v3

      - name: Run tests
        timeout-minutes: 40
        run: make test-helm
