name: Unit Tests UI
run-name: Unit Tests UI - ${{ github.run_id }} - @${{ github.actor }}

on:
  pull_request:
    paths:
      - '.github/workflows/unit-tests-ui.yaml'
      - 'web/**'
      - 'gen/proto/js/**'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'jest.config.js'
  merge_group:
    paths:
      - '.github/workflows/unit-tests-ui.yaml'
      - 'web/**'
      - 'gen/proto/js/**'
      - 'package.json'
      - 'yarn.lock'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'jest.config.js'

jobs:
  test:
    name: Test UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OSS Teleport
        uses: actions/checkout@v4

      - name: Determine Toolchain Versions
        run: |
          echo NODE_VERSION=$(make -s -C build.assets print-node-version) >> $GITHUB_ENV

      - name: Print versions
        run: |
          echo "node: ${NODE_VERSION}"

      - name: Setup Node Toolchain
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn dependencies
        run: bash web/packages/build/scripts/yarn-install-frozen-lockfile.sh

      - name: Run tests
        run: yarn test
