name: Unit tests
on:
  push:
  pull_request:

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    # Required by google cloud auth
    permissions:
      contents: read
      id-token: write
    # timeout-minutes: 10 TODO: Uncomment on production runner
    container: 
      image: public.ecr.aws/gravitational/teleport-buildbox:teleport11
      env:
        HELM_PLUGINS: /root/.local/share/helm/plugins # See Makefile:533, Dockerfile needs to be fixed
      volumes:
        - ${{ github.workspace }}:/workspace
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Install git 1.18+
        run: |
          apt-get -y update && apt-get -y install software-properties-common 
          add-apt-repository -y ppa:git-core/ppa
          apt-get -y update && apt-get -y install git
      - name: Checkout Teleport
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/671314886056/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: teleport-storage@just-terminus-366813.iam.gserviceaccount.com
      - name: Mark /workspace as git safe.directory
        run: |
          git config --global --add safe.directory /workspace
          git config --global --add safe.directory /workspace/webassets
      - name: Fetch go cache paths
        id: go-cache-paths
        run: |
          echo "go-build=$(go env GOCACHE)" >> $GITHUB_OUTPUT
          echo "go-mod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
      - name: Go build cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-unit-${{ hashFiles('/workspace/**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-build-unit-
      - name: Go mod cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-unit-${{ hashFiles('/workspace/**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-mod-unit-
      - name: Rust cargo cache
        uses: actions/cache@v3
        with:
          path: |
            /workspace/target
            /usr/local/cargo/registry
            /usr/local/cargo/git
          key: ${{ runner.os }}-cargo-unit-${{ hashFiles('/workspace/**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-unit-
      - name: Run tests (force)
        if: ${{ github.ref_name == 'master' }}
        run: |
          cd /workspace/.github/scripts
          go run ./cmd/unit-tests -target "$GITHUB_REF_NAME" -commit $GITHUB_SHA -bucket teleport-test-logs -a "test-logs/*.json" -build "$GITHUB_RUN_ID" -force

      - name: Run tests
        if: ${{ github.ref_name != 'master' }}
        run: |
          cd /workspace/.github/scripts
          go run ./cmd/unit-tests -target "$GITHUB_REF_NAME" -commit $GITHUB_SHA
